version: '3.8'
services:
  notion-page-to-html-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: notion-page-to-html-test
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
    command: |
      npm test
